<a href="https://colab.research.google.com/github/farhanfuadabir/Nurse-Care-Challenge-2020/blob/main/1D_CNN_Nurse_Care_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Sliding Window

In [ ]:
def sliding_window(df, num_datapoint = 50, slide_frac = 0.5):
  import pandas as pd
  import numpy as np
  from tqdm.notebook import tqdm
  acc_x = pd.DataFrame()
  acc_y = pd.DataFrame()
  acc_z = pd.DataFrame()
  label = pd.DataFrame()
  slide = (int)(num_datapoint * slide_frac)
  take_index = df['take'].unique()
  
  for i in tqdm(take_index):
    init = 0
    end = num_datapoint
    temp_df = df.loc[df['take'] == i]
    while end <= temp_df.shape[0]:
      acc_x = acc_x.append(temp_df['x'].iloc[init:end].reset_index(drop=True).transpose(),ignore_index=True)
      acc_y = acc_y.append(temp_df['y'].iloc[init:end].reset_index(drop=True).transpose(),ignore_index=True)
      acc_z = acc_z.append(temp_df['z'].iloc[init:end].reset_index(drop=True).transpose(),ignore_index=True)
      label = label.append(temp_df['label'].iloc[init:end].reset_index(drop=True).transpose(),ignore_index=True)
      init = init + slide
      end = end + slide
  label = label.median(axis=1)    
  
  print('acc_x = \n')
  display(acc_x)
  print('\n\n---------------\n\nacc_y = \n')
  display(acc_y)
  print('\n\n---------------\n\nacc_z = \n')
  display(acc_z)
  print('\n\n---------------\n\nlabel = \n')
  display(label)

  print('\n\nDone')

  return acc_x, acc_y, acc_z, label

In [ ]:
from joblib import load

train = load("/content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/TRAIN.joblib")
test = load("/content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/TEST.joblib")

print('Train set shape: ', train.shape)
print('Test set shape: ', test.shape)

Train set shape:  (4875587, 5)
Test set shape:  (1218899, 5)


In [ ]:
#----------------------------- Window Train Set ---------------------------------

acc_x_train, acc_y_train, acc_z_train, label_train = sliding_window(train, num_datapoint = 50, slide_frac = 0.5) 


acc_x = 



0         1         2   ...        47        48        49
0      -1.494000 -1.390386 -1.397248  ... -1.426300 -1.440865 -1.458243
1      -1.374090 -1.383826 -1.412885  ... -1.170377 -0.808965 -0.531719
2      -1.480759 -1.512208 -1.548208  ... -1.176636 -1.298229 -1.389032
3      -0.501445 -0.742364 -1.102681  ... -1.798793 -1.814588 -1.813965
4      -1.494343 -1.581829 -1.595693  ... -1.698032 -1.741683 -1.791903
...          ...       ...       ...  ...       ...       ...       ...
193841  1.915135  2.691692  2.731860  ...  5.015190  4.558085  3.988498
193842  5.037717  5.093065  4.422410  ...  2.044793  1.972195  2.431185
193843  3.464428  3.098891  2.902597  ... -0.082244 -1.412689 -2.091816
193844  3.101089  3.390654  2.925558  ...  1.993034  2.194591  2.149177
193845 -1.752598 -0.788187 -0.037677  ...  4.551001  3.270599  2.210095

[193846 rows x 50 columns]



---------------

acc_y = 



0         1          2   ...        47        48        49
0       8.925000  8.909091   8.932858  ...  8.969647  8.968744  8.962661
1       8.966086  8.954816   8.928484  ...  9.335028  9.443795  9.492250
2       8.952129  8.935702   8.916230  ...  8.878569  8.831805  8.759997
3       9.480318  9.462045   9.499919  ...  8.659076  8.634435  8.633050
4       8.657066  8.566434   8.544827  ...  8.903584  8.880088  8.884353
...          ...       ...        ...  ...       ...       ...       ...
193841  8.852632  9.582980  10.141510  ...  7.823805  8.236037  8.622647
193842  8.386586  8.466175   8.500948  ...  8.709515  8.629834  8.799729
193843  8.688997  8.304870   7.635105  ...  9.081464  9.392353  9.640439
193844  9.221139  9.522206   9.275805  ...  9.545650  8.754432  8.089133
193845  9.528342  9.180858   9.016198  ...  8.966161  8.466652  7.813790

[193846 rows x 50 columns]



---------------

acc_z = 



0         1         2   ...        47        48        49
0       0.550000  0.569191  0.563922  ...  0.532179  0.531834  0.555630
1       0.530319  0.527934  0.546904  ...  0.453729  0.328301  0.217100
2       0.572094  0.556515  0.522280  ...  0.950042  0.885868  0.850621
3       0.210828  0.300682  0.359864  ...  0.534957  0.517727  0.511640
4       0.855620  0.871091  0.871867  ...  0.556414  0.552470  0.561536
...          ...       ...       ...  ...       ...       ...       ...
193841  0.008559  0.017660  0.104570  ...  0.417517  0.136622 -0.119291
193842  0.247841  0.142703  0.172757  ...  2.014121  2.019234  1.921141
193843  0.022545  0.656435  1.481633  ...  0.122385  0.054672  0.116698
193844  1.753234  1.557951  1.415259  ...  0.114559  0.047305  0.104362
193845  0.102969  0.001321 -0.024733  ...  0.745719  1.713183  2.499758

[193846 rows x 50 columns]



---------------

label = 



0          1.0
1          1.0
2          1.0
3          1.0
4          1.0
          ... 
193841    12.0
193842    12.0
193843    12.0
193844    12.0
193845    12.0
Length: 193846, dtype: float64



Done


In [ ]:
#----------------------------- Export Train joblib ---------------------------------

from joblib import dump

export_path = '/content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/Windowed/'

print('Exporting joblib at: ', export_path + 'acc_x_train.joblib', '...', end='')
dump(acc_x_train, export_path + 'acc_x_train.joblib')
print('Done')
print('Exporting joblib at: ', export_path + 'acc_y_train.joblib', '...', end='')
dump(acc_y_train, export_path + 'acc_y_train.joblib')
print('Done')
print('Exporting joblib at: ', export_path + 'acc_z_train.joblib', '...', end='')
dump(acc_z_train, export_path + 'acc_z_train.joblib')
print('Done')
print('Exporting joblib at: ', export_path + 'label_train.joblib', '...', end='')
dump(label_train, export_path + 'label_train.joblib')
print('Done')

Exporting joblib at:  /content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/Windowed/acc_x_train.joblib ...Done
Exporting joblib at:  /content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/Windowed/acc_y_train.joblib ...Done
Exporting joblib at:  /content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/Windowed/acc_z_train.joblib ...Done
Exporting joblib at:  /content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/Windowed/label_train.joblib ...Done


In [ ]:
#----------------------------- Window Test Set ---------------------------------

acc_x_test, acc_y_test, acc_z_test, label_test = sliding_window(test, num_datapoint = 50, slide_frac = 0.5) 

'acc_x = \n'

0         1         2   ...        47        48        49
0     -1.123845 -1.101029 -1.602472  ... -0.854426 -1.374549 -1.763047
1     -1.458805 -1.880493 -2.160471  ... -3.861494 -3.949717 -4.325094
2     -1.820587 -1.672323 -1.726588  ... -2.210323 -2.234489 -2.311221
3     -3.179000 -2.970091 -3.008566  ... -3.837233 -3.306506 -2.056770
4     -4.064453 -4.124903 -3.091135  ... -5.434000 -5.415184 -5.646786
...         ...       ...       ...  ...       ...       ...       ...
48204  5.509862  5.217662  4.726953  ... -3.645738 -2.399439 -1.061153
48205 -0.076000 -0.828821 -1.212687  ...  6.474609  3.583654  0.689762
48206  0.129119  1.133441  2.443901  ...  8.840382  8.224925  7.633866
48207 -1.839268 -3.719298 -4.797336  ...  5.055339  4.938458  4.899422
48208  7.200623  7.004425  7.056017  ...  3.401267  3.088264  2.789229

[48209 rows x 50 columns]



---------------




'acc_y = \n'

0          1          2   ...        47         48         49
0      8.707319   8.475399   8.702346  ...  9.908491   9.648182   9.425817
1      8.303539   8.331722   8.550889  ...  8.507056   8.422583   8.041267
2      9.393181   9.452963   9.423135  ...  7.163152   7.137392   7.507263
3      7.623000   7.793118   7.719312  ...  8.547983   8.840723   9.280512
4      7.820336   7.861343   7.521748  ...  6.338481   7.010419   7.693519
...         ...        ...        ...  ...       ...        ...        ...
48204  8.385462   8.525602   8.656321  ...  8.953603   9.183679   9.315485
48205  9.883000  10.189782  10.342183  ...  2.786116   3.786756   5.003435
48206  9.904754   9.660969   9.212436  ...  1.807284   2.021934   2.538730
48207  6.245402   7.313405   8.039266  ...  7.247924   7.220417   7.305982
48208  3.271458   4.096624   4.881689  ...  9.758376  10.316206  10.783971

[48209 rows x 50 columns]



---------------




'acc_z = \n'

0         1         2   ...        47        48        49
0      0.183213  0.064056  0.035320  ...  0.268402  0.303412  0.238322
1      0.285025  0.278045  0.019949  ... -0.647383  0.049929  1.930436
2      0.112258  0.054565  0.117265  ...  5.951679  5.965638  5.646305
3      5.387000  5.393873  5.427118  ... -0.050496 -0.016525  0.152260
4      5.067571  4.814978  5.275901  ...  0.626819  0.733319  0.887854
...         ...       ...       ...  ...       ...       ...       ...
48204 -0.187174  0.049401  0.306283  ... -0.547430 -0.707685 -0.608642
48205  0.069000  0.128895  0.165633  ...  5.976816  6.898814  7.646663
48206  0.160104  0.121780  0.069606  ... -0.529716 -0.291357 -0.059647
48207  8.192733  8.538026  8.707340  ...  0.080826  0.074273  0.062044
48208  0.128770  0.257098  0.326759  ...  0.387763  0.346838  0.312200

[48209 rows x 50 columns]



---------------




'label = \n'

0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
         ... 
48204    12.0
48205    12.0
48206    12.0
48207    12.0
48208    12.0
Length: 48209, dtype: float64



Done


In [ ]:
#----------------------------- Export Test joblib ---------------------------------

from joblib import dump

export_path = '/content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/Windowed/'

print('Exporting joblib at: ', export_path + 'acc_x_test.joblib', '...', end='')
dump(acc_x_test, export_path + 'acc_x_test.joblib')
print('Done')
print('Exporting joblib at: ', export_path + 'acc_y_test.joblib', '...', end='')
dump(acc_y_test, export_path + 'acc_y_test.joblib')
print('Done')
print('Exporting joblib at: ', export_path + 'acc_z_test.joblib', '...', end='')
dump(acc_z_test, export_path + 'acc_z_test.joblib')
print('Done')
print('Exporting joblib at: ', export_path + 'label_test.joblib', '...', end='')
dump(label_test, export_path + 'label_test.joblib')
print('Done')

Exporting joblib at:  /content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/Windowed/acc_x_test.joblib ...Done
Exporting joblib at:  /content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/Windowed/acc_y_test.joblib ...Done
Exporting joblib at:  /content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/Windowed/acc_z_test.joblib ...Done
Exporting joblib at:  /content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/Windowed/label_test.joblib ...Done


In [ ]:
trial = pd.DataFrame(data={'take': [2,2,2,2,2,1,1,1,1,1], 
                           'x': [1,1,1,2,4,4,5,6,6,6], 
                           'y': [1,1,1,2,4,4,5,6,6,6], 
                           'z': [6,5,4,4,3,3,3,1,1,1], 
                           'label': [1,1,1,2,2,2,2,3,3,3]})
display(trial)
acc_x = pd.DataFrame()
acc_y = pd.DataFrame()
acc_z = pd.DataFrame()
label = pd.DataFrame()
slide = (int)(2 * 0.5)

#df = df.groupby('take').filter(lambda x: len(x) >= num_datapoint)
take_index = trial['take'].unique()
display(take_index)

take  x  y  z  label
0     2  1  1  6      1
1     2  1  1  5      1
2     2  1  1  4      1
3     2  2  2  4      2
4     2  4  4  3      2
5     1  4  4  3      2
6     1  5  5  3      2
7     1  6  6  1      3
8     1  6  6  1      3
9     1  6  6  1      3

array([2, 1])

In [ ]:
acc_x = pd.DataFrame()
for i in take_index:
    init = 0
    end = 2
    temp_df = trial.loc[trial['take'] == i]
    while end <= temp_df.shape[0]:
      # print('init = ', init)
      temp_x = temp_df['x'].iloc[init:end].reset_index(drop=True).transpose()
      
      acc_x = acc_x.append(temp_x,ignore_index=True)
      # acc_y = acc_y.append(temp_df['y'].iloc[init:end].to_frame().reset_index().transpose(),ignore_index=True)
      # acc_z = acc_z.append(temp_df['z'].iloc[init:end].to_frame().reset_index().transpose(),ignore_index=True)
      # label = label.append(temp_df['label'].iloc[init:end].to_frame().reset_index().transpose(),ignore_index=True)
      init = init + 1
      end = end + 1

display(acc_x)

0    1
0  1.0  1.0
1  1.0  1.0
2  1.0  2.0
3  2.0  4.0
4  4.0  5.0
5  5.0  6.0
6  6.0  6.0
7  6.0  6.0

In [ ]:
#bla = pd.DataFrame()
temp = train_1['x'].iloc[0:50].to_frame().transpose()
display(temp)
# temp = temp.
# display(temp)
bla = bla.append(temp,ignore_index=True)
display(bla)

0         1         2         3   ...       46      47        48        49
x -1.494 -1.390386 -1.397248 -1.423023  ... -1.41614 -1.4263 -1.440865 -1.458243

[1 rows x 50 columns]

0         1         2         3   ...       46      47        48        49
0 -1.494 -1.390386 -1.397248 -1.423023  ... -1.41614 -1.4263 -1.440865 -1.458243
1 -1.494 -1.390386 -1.397248 -1.423023  ... -1.41614 -1.4263 -1.440865 -1.458243
2 -1.494 -1.390386 -1.397248 -1.423023  ... -1.41614 -1.4263 -1.440865 -1.458243

[3 rows x 50 columns]

In [ ]:
import numpy as np
import pandas as pd

loaded = list()

a = np.array([[1,2,3],[4,5,6]]) 
print(a)
loaded.append(a)
loaded.append(a)
loaded.append(a)
print(loaded)

loaded = np.dstack(loaded)

# print(a)
print(loaded)
print(loaded.shape)


print('\n\n\n --------------------- \n\n\n')

B = pd.Series([2,3,4,5,6,7,8,9]).to_numpy()

print(B)
mul = 3
print(B.shape[0] % mul)
B = B[:-2]
B.reshape(-1,mul)


[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[1, 2, 3],
       [4, 5, 6]]), array([[1, 2, 3],
       [4, 5, 6]])]
[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]
(2, 3, 3)



 --------------------- 



[2 3 4 5 6 7 8 9]
2


array([[2, 3, 4],
       [5, 6, 7]])

# Dependencies

In [2]:
# cnn model
import numpy as np
import pandas as pd
from matplotlib import pyplot
from joblib import load, dump
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.utils import to_categorical

# Process Windowed Dataset for CNN

In [3]:
# load a single file as a numpy array
def load_file(filepath):
  dataframe = load(filepath)
  return dataframe.values
 
# load a list of files and return as a 3d numpy array
def load_group(filenames, path):
	loaded = list()
	for name in filenames:
		data = load_file(path + name)
		loaded.append(data)
	# stack group so that features are the 3rd dimension
	loaded = np.dstack(loaded)
	return loaded
 
# load a dataset group, such as train or test
def load_dataset_group(group, path):
	# load all 3 files as a single array
	filenames = ['acc_x_' + group + '.joblib', 'acc_y_' + group + '.joblib', 
              'acc_z_' + group + '.joblib']
	# load input data
	X = load_group(filenames, path)
	# load class output
	y = load_file(path + 'label_' + group + '.joblib')
	return X, y
 
# load the dataset, returns train and test X and y elements
def load_dataset(path):
  # load all train
  trainX, trainy = load_dataset_group('train', path)
  print('trainX shape: ', trainX.shape, '   |   trainy shape: ', trainy.shape)
  # load all test
  testX, testy = load_dataset_group('test', path)
  print('testX shape: ', testX.shape, '   |   testy shape: ', testy.shape)
  # zero-offset class values
  trainy = trainy - 1
  testy = testy - 1
  # one hot encode y
  trainy = to_categorical(trainy)
  testy = to_categorical(testy)
  print('Final Dataset shape: \n\nTrain Set: ', end='')
  print(trainX.shape, '<----->', trainy.shape, '\nTest Set: ', testX.shape, '<----->', testy.shape)
  return trainX, trainy, testX, testy

In [4]:
# load data
dataset_path = '/content/drive/MyDrive/NCC Train Test Set (Resampled 20Hz)/Split 80 20/Windowed/'
trainX, trainy, testX, testy = load_dataset(dataset_path)

trainX shape:  (193846, 50, 3)    |   trainy shape:  (193846,)
testX shape:  (48209, 50, 3)    |   testy shape:  (48209,)
Final Dataset shape: 

Train Set: (193846, 50, 3) <-----> (193846, 12) 
Test Set:  (48209, 50, 3) <-----> (48209, 12)


# CNN Model

In [6]:
from keras import backend as K

def recall_m(y_true, y_pred):
  true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
  possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
  recall = true_positives / (possible_positives + K.epsilon())
  return recall

def precision_m(y_true, y_pred):
  true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
  predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
  precision = true_positives / (predicted_positives + K.epsilon())
  return precision

def f1_m(y_true, y_pred):
  precision = precision_m(y_true, y_pred)
  recall = recall_m(y_true, y_pred)
  return 2*((precision*recall)/(precision+recall+K.epsilon()))

# fit and evaluate a model
def evaluate_model(trainX, trainy, testX, testy, verbose, epochs, batch_size):
  n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], trainy.shape[1]
  model = Sequential()
  model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(n_timesteps,n_features)))
  model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
  model.add(Dropout(0.5))
  model.add(MaxPooling1D(pool_size=2))
  model.add(Flatten())
  model.add(Dense(100, activation='relu'))
  model.add(Dense(n_outputs, activation='softmax'))
  model.compile(loss='categorical_crossentropy', optimizer='adam', 
                metrics=['categorical_accuracy', f1_m, precision_m, recall_m])
  # fit network
  # model.fit(trainX, trainy, epochs=epochs, batch_size=batch_size, verbose=verbose)
  # # evaluate model
  # _, accuracy = model.evaluate(testX, testy, batch_size=batch_size, verbose=0)
  import time
  t_start = time.clock()
  history = model.fit(trainX, trainy, epochs=epochs, batch_size=batch_size, verbose=verbose)

  t_end = time.clock()

  print('\n\n\n')

  #_, accuracy_train = model.evaluate(X_train, y_train)
  loss_train, accuracy_train, f1_score_train, precision_train, recall_train = model.evaluate(trainX, trainy, verbose=1)
  print('Train Accuracy: %.2f' % (accuracy_train*100))
  print('Train F1 Score: %.2f' % (f1_score_train*100))
  print('Train Time: ', t_end - t_start)

  t_start = time.clock()
  #_, accuracy_test = model.evaluate(X_test, y_test)
  loss_test, accuracy_test, f1_score_test, precision_test, recall_test = model.evaluate(testX, testy, verbose=1)
  print('Test Accuracy: %.2f' % (accuracy_test*100))
  print('Test F1 Score: %.2f' % (f1_score_test*100))
  t_end = time.clock()
  print('Test Time: ', t_end - t_start)

  import matplotlib.pyplot as plt
  #history = model.fit(X_train, y_train, validation_split=0.33, epochs=50, batch_size=500, verbose=1)
  # list all data in history
  #print(history.history.keys())
  # summarize history for accuracy

  plt.plot(history.history['categorical_accuracy'])
  plt.plot(history.history['val_categorical_accuracy'])
  plt.title('Model Accuracy')
  plt.ylabel('accuracy')
  plt.xlabel('epoch')
  plt.legend(['train', 'test'], loc='upper left')
  plt.show()

  return f1_score_test, history
 
# summarize scores
def summarize_results(scores):
	print(scores)
	m, s = np.mean(scores), np.std(scores)
	print('Accuracy: %.3f%% (+/-%.3f)' % (m, s))
 
# run an experiment
def run_experiment(repeats=10, verbose=True, epochs=10, batch_size=32):
  # repeat experiment
  scores = list()
  for r in range(repeats):
    score = evaluate_model(trainX, trainy, testX, testy, verbose, epochs, batch_size)
    score = score * 100.0
    print('>#%d: %.3f' % (r+1, score))
    scores.append(score)
  # summarize results
  summarize_results(scores)

## Train

In [ ]:
# for single iteration
score, history = evaluate_model(trainX, trainy, testX, testy, verbose=True, epochs=100, batch_size=32)
score = score * 100.0
print('Score:', '%.3f' % (score))

import matplotlib.pyplot as plt
plt.plot(history.history['categorical_accuracy'])
plt.plot(history.history['val_categorical_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

Epoch 1/100
6058/6058 [==============================] - 29s 4ms/step - loss: 1.0086 - categorical_accuracy: 0.6267 - f1_m: 0.5844 - precision_m: 0.7691 - recall_m: 0.4764
Epoch 2/100
6058/6058 [==============================] - 22s 4ms/step - loss: 0.8846 - categorical_accuracy: 0.6662 - f1_m: 0.6348 - precision_m: 0.7850 - recall_m: 0.5368
Epoch 3/100
6058/6058 [==============================] - 22s 4ms/step - loss: 0.8559 - categorical_accuracy: 0.6778 - f1_m: 0.6512 - precision_m: 0.7866 - recall_m: 0.5592
Epoch 4/100
6058/6058 [==============================] - 22s 4ms/step - loss: 0.8404 - categorical_accuracy: 0.6821 - f1_m: 0.6596 - precision_m: 0.7878 - recall_m: 0.5708
Epoch 5/100
6058/6058 [==============================] - 22s 4ms/step - loss: 0.8247 - categorical_accuracy: 0.6868 - f1_m: 0.6694 - precision_m: 0.7869 - recall_m: 0.5854
Epoch 6/100
6058/6058 [==============================] - 22s 4ms/step - loss: 0.7982 - categorical_accuracy: 0.6945 - f1_m: 0.6813 - precisi



```
# This is formatted as code
Epoch 1/10
6058/6058 [==============================] - 22s 4ms/step - loss: 1.0047 - categorical_accuracy: 0.6299 - f1_m: 0.5860 - precision_m: 0.7648 - recall_m: 0.4799
Epoch 2/10
6058/6058 [==============================] - 22s 4ms/step - loss: 0.8803 - categorical_accuracy: 0.6695 - f1_m: 0.6386 - precision_m: 0.7847 - recall_m: 0.5423
Epoch 3/10
6058/6058 [==============================] - 21s 3ms/step - loss: 0.8562 - categorical_accuracy: 0.6782 - f1_m: 0.6516 - precision_m: 0.7803 - recall_m: 0.5628
Epoch 4/10
6058/6058 [==============================] - 22s 4ms/step - loss: 0.8370 - categorical_accuracy: 0.6834 - f1_m: 0.6646 - precision_m: 0.7801 - recall_m: 0.5822
Epoch 5/10
6058/6058 [==============================] - 21s 3ms/step - loss: 0.8324 - categorical_accuracy: 0.6838 - f1_m: 0.6682 - precision_m: 0.7798 - recall_m: 0.5875
Epoch 6/10
6058/6058 [==============================] - 21s 4ms/step - loss: 0.8102 - categorical_accuracy: 0.6894 - f1_m: 0.6775 - precision_m: 0.7809 - recall_m: 0.6013
Epoch 7/10
6058/6058 [==============================] - 22s 4ms/step - loss: 0.7917 - categorical_accuracy: 0.6966 - f1_m: 0.6879 - precision_m: 0.7868 - recall_m: 0.6137
Epoch 8/10
6058/6058 [==============================] - 21s 3ms/step - loss: 0.7792 - categorical_accuracy: 0.7008 - f1_m: 0.6947 - precision_m: 0.7905 - recall_m: 0.6222
Epoch 9/10
6058/6058 [==============================] - 21s 3ms/step - loss: 0.7690 - categorical_accuracy: 0.7052 - f1_m: 0.7002 - precision_m: 0.7941 - recall_m: 0.6285
Epoch 10/10
6058/6058 [==============================] - 21s 3ms/step - loss: 0.7575 - categorical_accuracy: 0.7077 - f1_m: 0.7020 - precision_m: 0.7952 - recall_m: 0.6308


6058/6058 [==============================] - 17s 3ms/step - loss: 0.7706 - categorical_accuracy: 0.7162 - f1_m: 0.5843 - precision_m: 0.7127 - recall_m: 0.5500
Train Accuracy: 71.62
Train F1 Score: 58.43
Train Time:  282.6982549999999
1507/1507 [==============================] - 4s 3ms/step - loss: 1.0647 - categorical_accuracy: 0.6227 - f1_m: 0.5564 - precision_m: 0.6153 - recall_m: 0.5461
Test Accuracy: 62.27
Test F1 Score: 55.64
Test Time:  5.5919249999999465
Score: 55.639
```



In [ ]:
# run the experiment for interations
run_experiment(10, verbose=False, epochs=10, batch_size=32)

KeyboardInterrupt: ignored

# Random Forest Model

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier

# load label set again
trainy_2 = load_file(dataset_path + 'label_train.joblib')
testy_2 = load_file(dataset_path + 'label_test.joblib')

clf = RandomForestClassifier(verbose=True,n_jobs=-1)

clf.fit(trainX, trainy_2)
y_pred = clf.predict(testX)

# Evaluate Algorithm
print("\n\nConfusion Matrix: \n\n",confusion_matrix(testy_2,y_pred))
print("\n\nReport: \n\n",classification_report(testy_2,y_pred))
print("Accuracy: ",accuracy_score(testy_2,y_pred))

ValueError: ignored